package com.dilshan.chat_app.entity;

import jakarta.persistence.*;


import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Entity
@Table(name = "chat_rooms")
public class ChatRoom {

    public enum ChatType{
        SINGLE,
        GROUP
    }

    @Id // This is the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generated by the database
    private Long id;

    // Removed @GeneratedValue and @GenericGenerator from chatId
    // The UUID generation will be handled by the @PrePersist method
    @Column(name = "chat_id", unique = true, updatable = false, nullable = false)
    private String chatId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ChatType type;

    private String name;

    @ManyToMany
    @JoinTable(name = "chat_room_participants",
            joinColumns = @JoinColumn(name = "chat_room_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id"))
    private Set<User> participants = new HashSet<>();

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    public ChatRoom() {
    }

    public ChatRoom(Long id, String chatId, ChatType type, String name, Set<User> participants, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.chatId = chatId;
        this.type = type;
        this.name = name;
        this.participants = participants;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }


    public ChatRoom(String chatId, ChatType type, String name, Set<User> participants, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.chatId = chatId;
        this.type = type;
        this.name = name;
        this.participants = participants;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public ChatRoom(ChatType type, String name, Set<User> participants) {
        this.type = type;
        this.name = name;
        this.participants = participants;
    }

    public ChatRoom(ChatType type, Set<User> participants) {
        this(type, null, participants);
    }

    public Long getId() {
        return id;
    }

    // No setter for ID as it's generated
    // public void setId(Long id) { this.id = id; }

    public String getChatId() {
        return chatId;
    }

    // No setter for chatId as it's generated on persist and immutable
    // public void setChatId(String chatId) { this.chatId = chatId; }

    public ChatType getType() {
        return type;
    }

    public void setType(ChatType type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set<User> getParticipants() {
        return participants;
    }

    public void setParticipants(Set<User> participants) {
        this.participants = participants;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // No setter for createdAt as it's set on persist and immutable
    // public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @PrePersist
    protected void onCreate(){
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        // Generate UUID for chatId if it's not already set
        if(this.chatId == null || this.chatId.isEmpty()){ // Added check for empty string too
            this.chatId = java.util.UUID.randomUUID().toString();
        }
    }

    @PreUpdate
    protected void onUpdate(){
        this.updatedAt = LocalDateTime.now();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ChatRoom chatRoom = (ChatRoom) o;
        // If id is null, compare by chatId (for newly created entities before persistence)
        // Otherwise, compare by id
        if (id != null) {
            return Objects.equals(id, chatRoom.id);
        } else {
            // Ensure chatId is not null when comparing
            return Objects.equals(chatId, chatRoom.chatId);
        }
    }

    @Override
    public int hashCode() {
        // If id is null, use chatId for hashCode
        // Otherwise, use id
        // Ensure that if chatId is null (e.g., before @PrePersist), it doesn't cause issues.
        // For consistency, once an entity has an ID, use it for hashCode.
        return id != null ? Objects.hash(id) : Objects.hash(chatId != null ? chatId : System.identityHashCode(this));
    }

    @Override
    public String toString() {
        return "ChatRoom{" +
                "id=" + id +
                ", chatId='" + chatId + '\'' +
                ", type=" + type +
                ", name='" + name + '\'' +
                ", participantsCount=" + (participants != null ? participants.size() : 0) +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                '}';
    }
}
